server:
  port: 8081

spring:
  application:
    name: patient-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: true
      fail-fast: false
      import-check:
        enabled: false

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/db_patient?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        