server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/hp/Desktop/fsk/prj_rim/hospital-config-repo
          search-paths: '{application}'
          clone-on-start: true
          force-pull: true
          

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,restart
  endpoint:
    health:
      show-details: always